import { weightedChoice } from "./chance.js"

export class Alphabet {
    static alphabet = [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
    ]

    static alphabetScoreValues = {
        'A': 1,
        'B': 3,
        'C': 3,
        'D': 2,
        'E': 1,
        'F': 4,
        'G': 2,
        'H': 4,
        'I': 1,
        'J': 8,
        'K': 5,
        'L': 1,
        'M': 3,
        'N': 1,
        'O': 1,
        'P': 3,
        'Q': 10,
        'R': 1,
        'S': 1,
        'T': 1,
        'U': 1,
        'V': 4,
        'W': 4,
        'X': 8,
        'Y': 4,
        'Z': 10,
    }

    static alphabetWeightList = [
        9,
        2,
        2,
        4,
        12,
        2,
        3,
        2,
        9,
        1,
        1,
        4,
        2,
        6,
        8,
        2,
        1,
        6,
        4,
        6,
        4,
        2,
        2,
        1,
        2,
        1,
    ]

    static getRandomLetter() {
        return weightedChoice(this.alphabet, this.alphabetWeightList);
    }
}